name: Build and Deploy to DockerHub

on: 
  push:
    branches:
      - master
      - main
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
        - name: repository checkout
          uses: actions/checkout@v2
        
        - name: Login in to the docker
          uses: docker/login-action@v1
          with:
            username: ${{secrets.DOCKER_USERNAME}}
            password: ${{secrets.DOCKER_PASSWORD}}
          
        - name: build and push docker image
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./docker/Dockerfile.user
            push: true
            tags: charlesben/week-19:latest
        
        - name: verify push image
          run:  docker pull charlesben/week-19:latest
      
          

        - name: deploy to ec2
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_KEY }}
            script: |
              sudo docker pull charlesben/week-19:latest
              sudo docker stop web-app || true
              sudo docker rm web-app || true
              sudo docker run -d --name web-app -p 3005:3000 charlesben/week-19:latest

